# Simplex Recovery

In [5]:
import numpy as np

# set seed
np.random.seed(0)

In [6]:
# generate original basis
d = 5
k = 3
B = np.random.rand(d, k)
print(B)

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]]


In [ ]:
# generate topology over the basis
# assume that we observe a dxn matrix of convex combinations
# of the basis vectors. Let the weights vary smoothly
# across the matrix.